name: rc-person-detector
channels:
  - pytorch
  - nvidia
  - conda-forge
dependencies:
  - python=3.11
  - pytorch
  - torchvision
  - pytorch-cuda=12.1
  - numpy
  - pillow
  - matplotlib
  - pandas
  - jupyterlab
  - ipykernel
  - tensorboard
  - tqdm
  - pip
